name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install pipenv
      run: |
        pipx install pipenv
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        architecture: 'x64'
        cache: 'pipenv'
    - name: Display Python version
      run: python --version
    - name: Install dependencies
      run: pipenv sync
    - uses: pre-commit/action@v2.0.3
